In [1]:
import array as arr

Creating an array and traversing

In [7]:
a = arr.array('i', [1, 2, 3, 4, 5, 6])

for i in a:
    print(i)

1
2
3
4
5
6


Accessing individual elements through indexes

In [8]:
print(a[3])

4


Append any value to the array using append() method

In [9]:
a.append(6)
print(a)

array('i', [1, 2, 3, 4, 5, 6, 6])


Inserting value into the array

In [10]:
a.insert(0, -1)
print(a)

array('i', [-1, 1, 2, 3, 4, 5, 6, 6])


Extend python array using extend() method

In [11]:
my_array1 = arr.array('i', [10,11,12])
a.extend(my_array1)
print(a)

array('i', [-1, 1, 2, 3, 4, 5, 6, 6, 10, 11, 12])


Add items from list into array using fromlist() method

In [12]:
tempList = [20,21,22]
a.fromlist(tempList)
print(a)

array('i', [-1, 1, 2, 3, 4, 5, 6, 6, 10, 11, 12, 20, 21, 22])


Remove any array element using remove() method

In [13]:
a.remove(11)
print(a)

array('i', [-1, 1, 2, 3, 4, 5, 6, 6, 10, 12, 20, 21, 22])


Remove last array element using pop() method

In [14]:
a.pop()
print(a)

array('i', [-1, 1, 2, 3, 4, 5, 6, 6, 10, 12, 20, 21])


Fetch any element through its index using index() method

In [15]:
print(a.index(20))

10


Reverse a python array using reverse() method

In [16]:
a.reverse()
print(a)

array('i', [21, 20, 12, 10, 6, 6, 5, 4, 3, 2, 1, -1])


Get array buffer information through buffer_info() method

In [17]:
print(a.buffer_info())

(2003732524208, 12)


Check for number of occurrences of an element using count() method

In [18]:
a.append(21)
print(a.count(21))
print(a)

2
array('i', [21, 20, 12, 10, 6, 6, 5, 4, 3, 2, 1, -1, 21])


2D Arrays

In [31]:
import numpy as np

twoDArray = np.array([[11, 15, 10, 6], [10, 14, 11, 5], [12, 17, 12, 8], [15, 18, 14, 9]])
print(twoDArray)

[[11 15 10  6]
 [10 14 11  5]
 [12 17 12  8]
 [15 18 14  9]]


Inserting in a 2D array

In [32]:
newTwoDArray = np.insert(twoDArray, 1, [[1, 2, 3, 4]], axis=1)
print(newTwoDArray)

[[11  1 15 10  6]
 [10  2 14 11  5]
 [12  3 17 12  8]
 [15  4 18 14  9]]


In [34]:
newTwoDArray = np.append(newTwoDArray, [[7, 8, 9, 10, 11]], axis=0)
print(newTwoDArray)

[[11  1 15 10  6]
 [10  2 14 11  5]
 [12  3 17 12  8]
 [15  4 18 14  9]
 [ 7  8  9 10 11]]


Accessing an element in a 2D Array

In [35]:
def accessElement(array, r, c):
    if r >= len(array) and c >= len(array[0]):
        print("Incorrect index!")
    else:
        print(array[r][c])


accessElement(newTwoDArray, 2, 2)

17


Traversal

In [36]:
for i in range(len(newTwoDArray)):
    for j in range(len(newTwoDArray[0])):
        print(newTwoDArray[i][j], end=' ')

11 1 15 10 6 10 2 14 11 5 12 3 17 12 8 15 4 18 14 9 7 8 9 10 11 

Searching for an element

In [38]:
target = 17

for i in range(len(newTwoDArray)):
    for j in range(len(newTwoDArray[0])):
        if newTwoDArray[i][j] == target:
            print(i, j)
            break

2 2


Deletion

In [39]:
print(newTwoDArray)
newTwoDArray = np.delete(newTwoDArray, 0, axis=0)
print(newTwoDArray)

[[11  1 15 10  6]
 [10  2 14 11  5]
 [12  3 17 12  8]
 [15  4 18 14  9]
 [ 7  8  9 10 11]]
[[10  2 14 11  5]
 [12  3 17 12  8]
 [15  4 18 14  9]
 [ 7  8  9 10 11]]
